backend:
  name: git-gateway
  branch: main

local_backend: false

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "gallery"
    label: "Artwork Inventory"
    files:
      - file: "gallery.json"
        label: "Manage Portfolio Drawings"
        name: "portfolio_drawings"
        fields:
          - label: "All Artworks"
            name: "artworks"
            widget: "list"
            summary: "{{fields.title}} ({{fields.tag}})"
            fields:
              - { label: "Artwork Title", name: "title", widget: "string" }
              - { label: "Category Tag", name: "tag", widget: "string", hint: "Example: Gothic, Sketches, Oil Painting" }
              - { label: "Upload Image File", name: "image", widget: "image" }
